add disabled support for iOS
react-native-datetimepicker/datetimepicker pull request #412
Opened 2021-03-17 00:08 UTC by chrisdrackett

# Summary

Adds ability to disable this control on iOS

## Test Plan

Added ability to toggle to example app

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅      |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)
- [x] I have added automated tests, either in JS or e2e tests, as applicable

2021-03-17 11:19 UTC, vonovak commented on README.md
> +If true the user won't be able to toggle the switch.
```suggestion
If true, the user won't be able to interact with the view.
```

2021-03-17 11:20 UTC, vonovak requested changes
@chrisdrackett please just accept the suggested change and we're good to go, thank you!

2021-03-17 16:50 UTC, chrisdrackett commented
@vonovak done!

2021-03-17 17:45 UTC, vonovak approved these changes

2021-03-17 17:45 UTC, merged

2021-03-18 14:00 UTC, vonovak commented
:tada: This PR is included in version 3.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@react-native-community/datetimepicker/v/3.4.0)
- [GitHub release](https://github.com/react-native-datetimepicker/datetimepicker/releases/tag/v3.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: