[Android] Fix issue with minimumDate/maximumDate when using timeZoneOffsetInMinutes
react-native-datetimepicker/datetimepicker pull request #519
Opened 2021-10-08 14:37 UTC by PaitoAnderson

Fixes #518 

# Summary

On Android `setMinDate` and `setMaxDate` assumes the datetime passed will be in the device's local timezone, we now account for this by subtracting the minimumDate/maximumDate datetime offsets and also the provided timeZoneOffsetInMinutes.

## Test Plan

I've added a `toggleMinMaxDate` button in the demo project that shows this feature using two UTC min/max dates. Here is the before/after in -4 GMT.

Before:
![Screenshot_1633700803](https://user-images.githubusercontent.com/4108718/136569146-489d7f9d-bf0f-4e3f-b24a-29cfc8b8ef84.png)
After:
![Screenshot_1633700838](https://user-images.githubusercontent.com/4108718/136569144-beb878b5-1536-4ab1-946e-f4e70fcdc705.png)

### What's required for testing (prerequisites)?

Test using the `toggleMinMaxDate` button in the demo project.

FYI - I was unable to find a good way to pick a date using detox for e2e tests on Android.

### What are the steps to reproduce (after prerequisites)?

Using any negative timezone on the device should show this issue in the demo project.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)
- [x] I have added automated tests, either in JS or e2e tests, as applicable

2021-12-11 22:57 UTC, vonovak reviewed
hello and thank you for the PR!

I have added some small comments. Also, I'd really appreciate if you could add some e2e tests for this so that we know the android and ios behavior is the same, since the tz offset on android is not working 100%.

Selecting dates on android is kinda pain, the best way I know is in this PR: //github.com/react-native-datetimepicker/datetimepicker/pull/new/fix/use-resource-ids

thank you for your time! :)

2021-12-11 22:57 UTC, vonovak commented on android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
> +        int offset = TimeZone.getDefault().getOffset(c.getTimeInMillis()) - timeZoneOffsetInMilliseconds;
can you please extract this into a function `int getOffset()` that returns 0 or `TimeZone.getDefault().getOffset(c.getTimeInMillis()) - timeZoneOffsetInMilliseconds`?

then reuse the fn here and for datePicker.setMaxDate()

thank you :)

2021-12-11 22:57 UTC, vonovak commented on android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
> +      long timeZoneOffsetInMinutesFallback = args.getLong(RNConstants.ARG_TZOFFSET_MINS);
can this logic be xtracted into a separate fn and the `Integer timeZoneOffsetInMilliseconds = ` would be a one-liner?

thank would be nice, thank you

2021-12-14 01:27 UTC, PaitoAnderson commented
Thanks for reviewing and pointing me in the right direction on the android date picker selection for the e2e test.

2021-12-19 12:48 UTC, vonovak requested changes
hello and thanks so much, I'd like to ask for a few more small changes and then we're good to merge! :)

thanks

2021-12-19 12:48 UTC, vonovak commented on android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
> +  {
```suggestion
  private static Integer getTimeZoneOffset(Bundle args) {
```

2021-12-19 12:48 UTC, vonovak commented on example/App.js
> +
```suggestion
  const toggleMinMaxDate = () => {
    const startOfTodayUTC = sourceMoment.utc().startOf('day').toDate();
    setMinimumDate(
      maximumDate ? undefined : startOfTodayUTC,
    );
    const endOfTomorrowUTC = sourceMoment.utc().endOf('day').add(1, 'day').toDate();
    setMaximumDate(
      minimumDate
        ? undefined
        : endOfTomorrowUTC,
    );
  };

```

2021-12-19 12:48 UTC, vonovak commented on example/e2e/detoxTest.spec.js
> +          await uiDevice.pressDPadDown();
this seems like a simple for loop from 0 to n would already make sense here 🙂 
same thing below

2021-12-19 12:48 UTC, vonovak commented on example/e2e/detoxTest.spec.js
> +      await element(by.id('DateTimePickerScrollView')).scrollTo('bottom');
can you please use `elementById` for consistency? thanks

2021-12-19 14:49 UTC, PaitoAnderson commented
Thank you for reviewing! Let me know if you want anything else :)

2021-12-19 21:42 UTC, vonovak approved these changes

2021-12-19 21:48 UTC, merged

2021-12-19 22:01 UTC, vonovak commented
:tada: This issue has been resolved in version 5.0.2 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket: