feat: add timeZoneName props
react-native-datetimepicker/datetimepicker pull request #744
Opened 2023-03-25 18:46 UTC by wood1986

# Summary

There are 2 major issues when handling the timezone
1. It does not support daylight saving. 
1. #528 

My solution to these 2 issues are we should not re-interpute the timezone on JS side. JS only need to care UTC timestamp. All the timezone related should be handled on native side. Because OS has the full knowledge of all timezone

## Test Plan

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅ ❌     |
| Android |    ✅ ❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

2023-03-25 23:20 UTC, wood1986 commented
I want to get a feedback from maintainer before writing the test

2023-04-03 14:50 UTC, vonovak commented
hello and thanks for the PR!

I'm a little swamped right now with other work that pays the bills and the PR is rather large so it will take me some time to get back to this.

Thank you for you patience! 🙂

2023-04-14 22:05 UTC, wood1986 commented
Any update?

2023-05-08 06:10 UTC, wood1986 commented
It has been a month. Any update?

2023-05-12 17:01 UTC, vonovak requested changes
Hello and thank you for your PR!
firstly, thank you for taking a stab at this long-term issue. It is one that I was planning on tackling but didn't manage to get to it due to being involved elsewhere. Also, thank you for your patience with getting back to you.

I do agree with the approach of removing JS from the equation and having the date logic live in the native land, so that's good!

I added a few comments that should result into making the code better. 

When they are resolved, docs need to be updated as well. CI also needs to be green before merging.

To wrap up, this is a good direction AFAICT. Please address the review / reply to the comments if you disagree with them. Looking forward to merging! 🚀

2023-05-13 06:38 UTC, wood1986 commented on android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java
> +  private static final HashSet TIMEZONE_IDS = new HashSet<>(Arrays.asList(TimeZone.getAvailableIDs()));
If I do not this, then it will be a O(n) search for each create. Now it does once and use it afterwards in O(log n).

2023-05-13 06:52 UTC, wood1986 commented on android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java
> +  private static final HashSet TIMEZONE_IDS = new HashSet<>(Arrays.asList(TimeZone.getAvailableIDs()));
I want to resolve conversation. Feel free to reactivate it

2023-05-13 07:10 UTC, wood1986 commented on android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
> +        datePicker.updateDate(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH));
Good call

2023-05-13 07:25 UTC, wood1986 commented on android/src/main/java/com/reactcommunity/rndatetimepicker/TimePickerModule.java
> +        result.putDouble("utcOffset", calendar.getTimeZone().getRawOffset() / 1000 / 60);
Good call

2023-05-13 08:28 UTC, wood1986 commented
I fixed the all comments and have not finished yet. Now I can fix the test as you give me a green light and I will do it tomorrow

2023-05-13 20:07 UTC, wood1986 commented
Hey @vonovak, I am unable to run e2e test both locally and remotely with the same error https://app.circleci.com/pipelines/github/react-native-datetimepicker/datetimepicker/1220/workflows/e7c6c6c6-6cf9-4fa5-8b63-d9cba4df6e6f/jobs/3823/parallel-runs/0/steps/0-115

2023-05-15 11:41 UTC, vonovak commented on ios/RNDateTimePickerManager.m
> +  RCTLogWarn(@"'%@' does not exist in NSTimeZone.knownTimeZoneNames fallback to localTimeZone=%@", json, NSTimeZone.localTimeZone.name);
this warning will currently log even for cases when it shouldn't

2023-05-15 11:43 UTC, vonovak commented on ios/fabric/RNDateTimePickerComponentView.mm
> +            RCTLogWarn(@"'%@' does not exist in NSTimeZone.knownTimeZoneNames fallback to localTimeZone=%@", timeZoneName, NSTimeZone.localTimeZone.name);
I believe this will log even when it shouldn't

2023-05-15 12:00 UTC, vonovak commented
> Hey @vonovak, I am unable to run e2e test both locally and remotely with the same error 


see https://github.com/react-native-datetimepicker/datetimepicker/pull/758 - that should fix it

2023-06-20 20:19 UTC, vonovak commented
@wood1986 if you integrate the latest master, you should be able to run the example app and e2e tests. Let me know if you need any help, thanks! 👍

2023-07-08 07:06 UTC, wood1986 commented
@vonovak, I am still unable to run the e2e test. It shows

![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/5212215/0612d0e0-b074-4b76-9f63-ca88620b5c51)

2023-07-08 09:17 UTC, vonovak commented
There are two ways: 
1) remove the  utilBinaryPaths entry in detoxrc 

2) run the tests on a "vanilla" emulator without Google services installed. You can create one from the command line the same way it's done in circle ci, see the circle ci config file, android/create-avd step.

You'll see the exact command if you look at some previous ci runs in circle ci. I'm away from keyboard so cannot give the exact command.

Thank you! 👍

2023-07-09 19:02 UTC, wood1986 commented
Hey @vonovak, Now, I can run the test and I have fixed all the tests except tz related test cases. Thanks for that.

I want to completely remove all tzOffsetMinutes as I do not want to spend time on writing test for tzOffsetMinutes. What is your thought?

2023-07-09 20:45 UTC, vonovak commented
Please keep the code for tzOffsetMinutes the way it is (don't remove it, don't add tests).

What would be appreciated though is that if someone uses the tzOffsetMinutes prop, they get a depreciation warning, asking them to use the new prop instead. Thank you! 👍

2023-07-10 07:11 UTC, wood1986 commented
Now, I cannot run e2e test for iOS. It crashes on launch but I can launch it without detox

2023-07-10 08:35 UTC, vonovak commented
@wood1986 in CI, the ios tests appear to run just fine, so if they are crashing for you, it seems it's something that is present with you locally.
Is your branch up to date with master branch? It shouldn't really matter but I recently updated detox to latest stable... Not sure really.

Also, not sure why, as the tests are passing on Android, but I see failures with label not matching expectation (ax.id = "utcTime"; text = "2000-01-01T14:44:00Z", expected: toHaveText('2021-11-13T14:44:00Z') and trying to scroll `com.facebook.react.views.scroll.ReactHorizontalScrollView` (such component won't exists on ios).

In case you end up running out of time / patience, let me know and I can take it over the finish line, most of the work is done afaict. Thank you! 👍

2023-07-10 15:27 UTC, wood1986 commented
Thanks @vonovak 

I have not updated the test for iOS yet. android is completed except one test case in new architecture. 

My branch is up to date and it has all the latest change from master. Please run it on your side and let me know how I can run it locally. I was using iOS 16 and iPhone 14 simulator

2023-07-12 12:19 UTC, wood1986 commented
Hey @vonovak, Finally, I have just updated all the the tests. The test is a bit unstable. Only you can rerun the test. Please re-review everything as I did a force push.

By the way, I am still unable to run the test on iOS and I was using the build machine result to fix the tests

2023-08-02 10:56 UTC, vonovak commented
hello @wood1986 thank you for your work, and sorry to keep you waiting, I'm going to take a look at this next week! 👍

2023-08-29 13:08 UTC, vonovak approved these changes

2023-08-29 13:12 UTC, merged

2023-08-29 13:18 UTC, vonovak commented
@wood1986 thank you for your patience and your PR, it'll be released soon! 🙁 💯

2023-08-29 13:33 UTC, vonovak commented
:tada: This issue has been resolved in version 7.5.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket: