Added React Native version support table README.md
react-native-datetimepicker/datetimepicker pull request #899
Opened 2024-05-16 19:18 UTC by JDMathew

# Summary
I ran into build issues when installing this via storybook. It was unclear that the latest version of `datetimepicker` was not supported with older versions of react-native. I spent a while figuring this out though other issues and it would be good to include a version support table in the readme so others don't have to figure out backwards compatibility issues

## Checklist

- [ ] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

2024-05-21 15:28 UTC, vonovak commented on README.md
> +|      0.7.0+          |  7.0.1+  |
thank you for your PR!

you probably have "0" missing here and on line 154

2024-05-21 15:29 UTC, vonovak requested changes
thank you for your PR! Can you fix the small stuff (see comment)

2024-05-23 03:30 UTC, JDMathew commented
> thank you for your PR! Can you fix the small stuff (see comment)



> thank you for your PR! Can you fix the small stuff (see comment)

@vonovak, I have updated the PR, let me know if there is anything else.

2024-05-23 06:42 UTC, vonovak commented
@JDMathew the table still mentions RN 0.7.0 which probably should be 0.70.0?

2024-05-23 07:52 UTC, JDMathew commented
> @JDMathew the table still mentions RN 0.7.0 which probably should be 0.70.0?

Ah yes, sorry about that @vonovak, I updated 152 and missed 153. Should be correct now

2024-05-23 12:23 UTC, vonovak commented on README.md
> +|      <0.7.0          | <=7.0.0  |
```suggestion
|      <0.70.0         | <=7.0.0  |
```

2024-05-23 12:23 UTC, vonovak commented on README.md
> +|      <0.70.0         | <=7.0.0  |
```suggestion
|     <0.70.0          | <=7.0.0  |
```

2024-05-23 21:04 UTC, vonovak approved these changes

2024-05-23 21:04 UTC, merged