feat: Add set first day week android
react-native-datetimepicker/datetimepicker pull request #902
Opened 2024-05-30 09:17 UTC by JoshBarnesD

# Summary

This feature provides the optional **firstDayOfWeek** functionality to the DatePicker on Android (currently only available in Windows). I was looking for tasks to get started with in the project and I saw this was a pending issue [#196](https://github.com/react-native-datetimepicker/datetimepicker/issues/196), so I decided to implement it.

Although the issue itself is quite old, hopefully it is still useful for someone.

### How did you implement the solution?

As suggested in the issue thread, https://developer.android.com/reference/android/widget/DatePicker#setFirstDayOfWeek(int) provides the functionality to the Android DatePicker so that is what was used to implement it. The rest was simply bridging the props from React Native component to Android. 

The `firstDayOfWeek` prop accepts the `DAY_OF_WEEK` constant to set the first day of the week.

NOTE: The `DAY_OF_WEEK` constant was used for consistency between the original Windows implementation and the new Android one. This does however mean that once the prop is parsed in the Android component it adds a +1 to it since the integers for setFirstDayOfWeek are 1-indexed instead of 0-indexed.

## Test Plan

Some examples of the UI changes when selecting different firstDayOfWeek:

| firstDayOfWeek set to Sunday | firstDayOfWeek set to Wednesday |
| ------- | :---------: |
| ![Screenshot 2024-05-29 at 15 40 31](https://github.com/react-native-datetimepicker/datetimepicker/assets/125880121/8042b9cc-268a-45a1-8690-5fdec57e87c0) | ![Screenshot 2024-05-29 at 15 51 25](https://github.com/react-native-datetimepicker/datetimepicker/assets/125880121/31200b8e-4c15-49b7-a240-a79ca6f358e9) |

![Screenshot 2024-05-30 at 10 29 54](https://github.com/react-native-datetimepicker/datetimepicker/assets/125880121/8b527f76-a162-4e72-87aa-125d023650b2)
_(Ran e2e tests for release on an emulated Pixel 6 Pro with API 30 and phone TZ set to Prague)_

### What's required for testing (prerequisites)?

e2e tests have been added to the project checking the functionality. These detox tests are only run on Android.

### What are the steps to reproduce (after prerequisites)?

I have added a row of buttons to the example App which allow swapping the `firstDayOfWeek` for any day of the week. These are used in the e2e tests. I have also added a line to the upper info section of the example App which shows the current `firstDayOfWeek` value (defaults to Sunday).

## Comments

Some of the included changes modify existing e2e tests as they seem to have stopped working due to the UI changes done to the example App. Some of these changes include:

* Added scroll down/up to some tests depending on necessity due to added buttons pushing some content out of view.
* Added `.multiTap(2)` instead of `.tap()` to some tests as they occasionally failed. I suspect this is caused by the button trying to be tapped being inside a horizontal scrollview that doesn't finish scrolling before the tap on the button is triggered.

As a side note, I have seen that there are a few e2e tests that fail on iOS (even on master) when I test them locally, specifically those that use the `spinner` implementation of the `DateTimePicker`.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)
- [X] I have added automated tests, either in JS or e2e tests, as applicable

2024-05-30 14:14 UTC, vonovak requested changes
Thank you, I like this!! :)

especially the detailed description

2024-05-31 09:04 UTC, JoshBarnesD commented on example/e2e/detoxTest.spec.js
> +  describe(':android: firstDayOfWeek functionality', () => {
Great suggestion, implemented it and also added a new helper function to traverse the Calendar when selecting a specific day

2024-06-03 13:52 UTC, JoshBarnesD commented on example/App.js
> +            <View style={styles.firstDayOfWeekContainer}>
I will revert the changes to the tests that add scrolling and see if I can find a valid device for iOS and Android that will pass the tests without scrolling, will get back to you shortly

2024-06-03 14:56 UTC, vonovak approved these changes

2024-06-03 14:56 UTC, merged

2024-06-03 15:32 UTC, vonovak commented
:tada: This issue has been resolved in version 8.1.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket: